name: Tests

on: [push, pull_request]

jobs:
 build-and-run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v22
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Run Tests
      run: |
        nix run .#test
